# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.srcs/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/design_1_FourBitAdder_0_0.xci
# IP: The module: 'design_1_FourBitAdder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_0_0/design_1_FullAdder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_0_0 || ORIG_REF_NAME==design_1_FullAdder_0_0} -quiet] -quiet

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_1_0/design_1_FullAdder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_1_0 || ORIG_REF_NAME==design_1_FullAdder_1_0} -quiet] -quiet

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_2_0/design_1_FullAdder_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_2_0 || ORIG_REF_NAME==design_1_FullAdder_2_0} -quiet] -quiet

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_3_0/design_1_FullAdder_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_3_0 || ORIG_REF_NAME==design_1_FullAdder_3_0} -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_0_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FullAdder_0_0 || ORIG_REF_NAME==design_1_FullAdder_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_1_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FullAdder_1_0 || ORIG_REF_NAME==design_1_FullAdder_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_2_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FullAdder_2_0 || ORIG_REF_NAME==design_1_FullAdder_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_3_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FullAdder_3_0 || ORIG_REF_NAME==design_1_FullAdder_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FourBitAdder_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.gen/sources_1/bd/design_1/design_1_ooc.xdc

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.srcs/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/design_1_FourBitAdder_0_0.xci
# IP: The module: 'design_1_FourBitAdder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_0_0/design_1_FullAdder_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_0_0 || ORIG_REF_NAME==design_1_FullAdder_0_0} -quiet] -quiet

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_1_0/design_1_FullAdder_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_1_0 || ORIG_REF_NAME==design_1_FullAdder_1_0} -quiet] -quiet

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_2_0/design_1_FullAdder_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_2_0 || ORIG_REF_NAME==design_1_FullAdder_2_0} -quiet] -quiet

# IP: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_3_0/design_1_FullAdder_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_3_0 || ORIG_REF_NAME==design_1_FullAdder_3_0} -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_0_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FullAdder_0_0 || ORIG_REF_NAME==design_1_FullAdder_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_1_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FullAdder_1_0 || ORIG_REF_NAME==design_1_FullAdder_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_2_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FullAdder_2_0 || ORIG_REF_NAME==design_1_FullAdder_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_3_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_FullAdder_3_0 || ORIG_REF_NAME==design_1_FullAdder_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FourBitAdder_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.gen/sources_1/bd/design_1/design_1_ooc.xdc
