# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Reusables/Nexys-A7-100T-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FullAdder_0_0/design_1_FullAdder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_0_0 || ORIG_REF_NAME==design_1_FullAdder_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FullAdder_1_0/design_1_FullAdder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_1_0 || ORIG_REF_NAME==design_1_FullAdder_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FullAdder_2_0/design_1_FullAdder_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_2_0 || ORIG_REF_NAME==design_1_FullAdder_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FullAdder_3_0/design_1_FullAdder_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FullAdder_3_0 || ORIG_REF_NAME==design_1_FullAdder_3_0} -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/4BitAdder/4BitAdder.gen/sources_1/bd/design_1/design_1_ooc.xdc
