# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/vikto/Experiments/Microblaze_Test3/Microblaze_Test3.srcs/sources_1/bd/design_1/ip/design_1_PWM_Notes_0_0/design_1_PWM_Notes_0_0.xci
# IP: The module: 'design_1_PWM_Notes_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vikto/Experiments/Microblaze_Test3/Microblaze_Test3.gen/sources_1/bd/design_1/ip/design_1_PWM_Notes_0_0/PWM_test.srcs/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PWM_Notes_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/vikto/Experiments/Microblaze_Test3/Microblaze_Test3.srcs/sources_1/bd/design_1/ip/design_1_PWM_Notes_0_0/design_1_PWM_Notes_0_0.xci
# IP: The module: 'design_1_PWM_Notes_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vikto/Experiments/Microblaze_Test3/Microblaze_Test3.gen/sources_1/bd/design_1/ip/design_1_PWM_Notes_0_0/PWM_test.srcs/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PWM_Notes_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
