# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/vikto/Experiments/MicroblazeTest2/MicroblazeTest2.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_10/design_1_axi_gpio_0_10.xci
# IP: The module: 'design_1_axi_gpio_0_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vikto/Experiments/MicroblazeTest2/MicroblazeTest2.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_10/design_1_axi_gpio_0_10_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_10'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/MicroblazeTest2/MicroblazeTest2.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_10/design_1_axi_gpio_0_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/MicroblazeTest2/MicroblazeTest2.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_10/design_1_axi_gpio_0_10.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/vikto/Experiments/MicroblazeTest2/MicroblazeTest2.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_10/design_1_axi_gpio_0_10.xci
# IP: The module: 'design_1_axi_gpio_0_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vikto/Experiments/MicroblazeTest2/MicroblazeTest2.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_10/design_1_axi_gpio_0_10_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/MicroblazeTest2/MicroblazeTest2.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_10/design_1_axi_gpio_0_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/vikto/Experiments/MicroblazeTest2/MicroblazeTest2.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_10/design_1_axi_gpio_0_10.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
