set_property SRC_FILE_INFO {cfile:c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_3_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc rfile:../../../BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_3_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc id:1 order:EARLY scoped_inst:U0/design_1_i/FullAdder_3/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_2_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc rfile:../../../BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_2_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc id:2 order:EARLY scoped_inst:U0/design_1_i/FullAdder_2/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_1_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc rfile:../../../BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_1_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc id:3 order:EARLY scoped_inst:U0/design_1_i/FullAdder_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_0_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc rfile:../../../BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/sources_1/bd/design_1/ip/design_1_FullAdder_0_0/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc id:4 order:EARLY scoped_inst:U0/design_1_i/FullAdder_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/vikto/Experiments/BCDAdder/BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc rfile:../../../BCDAdder.gen/sources_1/bd/design_1/ip/design_1_FourBitAdder_0_0/4BitAdder.srcs/constrs_1/imports/Reusables/Nexys-A7-100T-Master.xdc id:5 order:EARLY scoped_inst:U0} [current_design]
current_instance U0/design_1_i/FullAdder_3/U0
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property src_info {type:SCOPED_XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { B }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property src_info {type:SCOPED_XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { Cin }]; #IO_L6N_T0_D08_VREF_14 Sch=sw[2]
set_property src_info {type:SCOPED_XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { S }]; #IO_L18P_T2_A24_15 Sch=led[0]
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { Cout }]; #IO_L24P_T3_RS1_15 Sch=led[1]
current_instance
current_instance U0/design_1_i/FullAdder_2/U0
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property src_info {type:SCOPED_XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { B }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property src_info {type:SCOPED_XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { Cin }]; #IO_L6N_T0_D08_VREF_14 Sch=sw[2]
set_property src_info {type:SCOPED_XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { S }]; #IO_L18P_T2_A24_15 Sch=led[0]
set_property src_info {type:SCOPED_XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { Cout }]; #IO_L24P_T3_RS1_15 Sch=led[1]
current_instance
current_instance U0/design_1_i/FullAdder_1/U0
set_property src_info {type:SCOPED_XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property src_info {type:SCOPED_XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { B }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property src_info {type:SCOPED_XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { Cin }]; #IO_L6N_T0_D08_VREF_14 Sch=sw[2]
set_property src_info {type:SCOPED_XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { S }]; #IO_L18P_T2_A24_15 Sch=led[0]
set_property src_info {type:SCOPED_XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { Cout }]; #IO_L24P_T3_RS1_15 Sch=led[1]
current_instance
current_instance U0/design_1_i/FullAdder_0/U0
set_property src_info {type:SCOPED_XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property src_info {type:SCOPED_XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { B }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property src_info {type:SCOPED_XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { Cin }]; #IO_L6N_T0_D08_VREF_14 Sch=sw[2]
set_property src_info {type:SCOPED_XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { S }]; #IO_L18P_T2_A24_15 Sch=led[0]
set_property src_info {type:SCOPED_XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { Cout }]; #IO_L24P_T3_RS1_15 Sch=led[1]
current_instance
current_instance U0
set_property src_info {type:SCOPED_XDC file:5 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { CLK }]; #IO_L12P_T1_MRCC_35 Sch=clk100mhz
set_property src_info {type:SCOPED_XDC file:5 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { CLK }];
set_property src_info {type:SCOPED_XDC file:5 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { Cin }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property src_info {type:SCOPED_XDC file:5 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { A_0 }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property src_info {type:SCOPED_XDC file:5 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { A_1 }]; #IO_L6N_T0_D08_VREF_14 Sch=sw[2]
set_property src_info {type:SCOPED_XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R15   IOSTANDARD LVCMOS33 } [get_ports { A_2 }]; #IO_L13N_T2_MRCC_14 Sch=sw[3]
set_property src_info {type:SCOPED_XDC file:5 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R17   IOSTANDARD LVCMOS33 } [get_ports { A_3 }]; #IO_L12N_T1_MRCC_14 Sch=sw[4]
set_property src_info {type:SCOPED_XDC file:5 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T18   IOSTANDARD LVCMOS33 } [get_ports { B_0 }]; #IO_L7N_T1_D10_14 Sch=sw[5]
set_property src_info {type:SCOPED_XDC file:5 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { B_1 }]; #IO_L17N_T2_A13_D29_14 Sch=sw[6]
set_property src_info {type:SCOPED_XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R13   IOSTANDARD LVCMOS33 } [get_ports { B_2 }]; #IO_L5N_T0_D07_14 Sch=sw[7]
set_property src_info {type:SCOPED_XDC file:5 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T8    IOSTANDARD LVCMOS18 } [get_ports { B_3 }]; #IO_L24N_T3_34 Sch=sw[8]
set_property src_info {type:SCOPED_XDC file:5 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { S_0 }]; #IO_L18P_T2_A24_15 Sch=led[0]
set_property src_info {type:SCOPED_XDC file:5 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { S_1 }]; #IO_L24P_T3_RS1_15 Sch=led[1]
set_property src_info {type:SCOPED_XDC file:5 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { S_2 }]; #IO_L17N_T2_A25_15 Sch=led[2]
set_property src_info {type:SCOPED_XDC file:5 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { S_3 }]; #IO_L8P_T1_D11_14 Sch=led[3]
set_property src_info {type:SCOPED_XDC file:5 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { Cout }]; #IO_L7P_T1_D09_14 Sch=led[4]
